### ISSUE TITLE
Convert .txt (Darknet) annotations to (PASCAL VOC) .xml annotations.

### ISSUE THREAD

**Issue by farhantandia** [MuhammadAsadJaved/Important-shells#1]
is not working,
![image](https://user-images.githubusercontent.com/17233457/108576130-65ab3480-7357-11eb-9f57-cef5bc34d33e.png)
or do I missed something?

**Comment by MuhammadAsadJaved** [comment]
@farhantandia 
Hi, Please try to change `int` to `float`   at line `116, 121, 126 and 131` 
For example like this 
original code: `xmin_txt = doc.createTextNode(str(int((float(objbuds[1])))))`
New code:  `xmin_txt = doc.createTextNode(str(float(objbuds[1])))`

If still doesn't work, then please upload a .txt annotation and let me try.

**Comment by farhantandia** [comment]
it's working but the result is not the same as if manually annotate using labelimg, you can check the file attached below.

[Data.zip](https://github.com/MuhammadAsadJaved/Important-shells/files/6013860/Data.zip)

**Comment by MuhammadAsadJaved** [comment]
Sorry, there was a mistake. let me correct it. 

There are two things. 

1- it's a mistake in code.  At line  116 and126 similarly at line 121 and 131 , I used same values. it should be [0], [1], [2], [3]  or [1], [2], [3] , [4] .

2- Please keep in mind in .txt annotations the values are different from .xml, these values are scaled with a factor in the .txt, so while converting .txt back to .xml you should multiply with the same factor. 

Now tell me what exaclty you want to do. I will send you code accordingly. 
You have a dataset with images and .txt annotations? now you want to convert to .xml?

**Comment by farhantandia** [comment]
Yes because my previous data using yolo format , I want train with different object detection model. Thanks.

**Comment by MuhammadAsadJaved** [comment]
OK. Wait please.

**Comment by MuhammadAsadJaved** [comment]
Hi, Please try this file and let me know if it works. 
I do not have the environment, so I am unable to test. 

[code.txt.txt](https://github.com/MuhammadAsadJaved/Important-shells/files/6014027/code.txt.txt)

**Comment by farhantandia** [comment]
`Traceback (most recent call last):
  File "d:/yolotoxml.py", line 182, in <module>
    writeXml(temp, img_name, width, height, obj, filename)
  File "d:/yolotoxml.py", line 117, in writeXml
    xmin_txt = doc.createTextNode(float(objbuds[1]))
  File "C:\Users\farha\anaconda3\envs\tensorflow_gpu\lib\xml\dom\minidom.py", line 1658, in createTextNode
    raise TypeError("node contents must be a string")
TypeError: node contents must be a string`
got error

**Comment by MuhammadAsadJaved** [comment]
> `Traceback (most recent call last): File "d:/yolotoxml.py", line 182, in <module> writeXml(temp, img_name, width, height, obj, filename) File "d:/yolotoxml.py", line 117, in writeXml xmin_txt = doc.createTextNode(float(objbuds[1])) File "C:\Users\farha\anaconda3\envs\tensorflow_gpu\lib\xml\dom\minidom.py", line 1658, in createTextNode raise TypeError("node contents must be a string") TypeError: node contents must be a string`
> got error

Let's try again. 

[code.txt](https://github.com/MuhammadAsadJaved/Important-shells/files/6014076/code.txt)

**Comment by MuhammadAsadJaved** [comment]
I have set up environment now. I did not use python in Windows before. I will check and test it, then update code.

**Comment by MuhammadAsadJaved** [comment]
@farhantandia  It's working fine now. 

After converting .xml , you can verify by drawing bounding boxes using Draw bounding box shell in my repo. 
https://github.com/MuhammadAsadJaved/Important-shells#draw-bounding-boxes-on-all-images

[code.txt](https://github.com/MuhammadAsadJaved/Important-shells/files/6014161/code.txt)

**Comment by farhantandia** [comment]
It works now, thanks. I will inform you if it is able to train and test successfully.
